#Se crea el volumen claim asociado al volumen local de la app MySQL.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv 
spec:
 storageClassName: manual
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 5Gi
